-- version 2 adds tables n data for encounters!
-- Tables
CREATE TABLE "encounters" ( `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `NAME` TEXT );
CREATE TABLE "enemies" ( `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `NAME` TEXT, `CR` TEXT, `REFERENCE` TEXT );
CREATE TABLE "encounterenemies" ( `ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `ENCOUNTER_ID` INTEGER, `ENEMY_ID` INTEGER, `QUANTITY` INTEGER );
-- Data
insert into 'enemies' ('name','cr','reference') values ('Frog', '0', 'MM 322');
insert into 'enemies' ('name','cr','reference') values ('Sea Horse', '0', 'MM 337');
insert into 'enemies' ('name','cr','reference') values ('Awakened Shrub', '0', 'MM 317');
insert into 'enemies' ('name','cr','reference') values ('Baboon', '0', 'MM 318');
insert into 'enemies' ('name','cr','reference') values ('Badger', '0', 'MM 318');
insert into 'enemies' ('name','cr','reference') values ('Bat', '0', 'MM 318');
insert into 'enemies' ('name','cr','reference') values ('Cat', '0', 'MM 320');
insert into 'enemies' ('name','cr','reference') values ('Crab', '0', 'MM 320');
insert into 'enemies' ('name','cr','reference') values ('Crawling Claw', '0', 'MM 44');
insert into 'enemies' ('name','cr','reference') values ('Deer', '0', 'MM 321');
insert into 'enemies' ('name','cr','reference') values ('Eagle', '0', 'MM 322');
insert into 'enemies' ('name','cr','reference') values ('Giant Fire Beetle', '0', 'MM 325');
insert into 'enemies' ('name','cr','reference') values ('Goat', '0', 'MM 330');
insert into 'enemies' ('name','cr','reference') values ('Hawk', '0', 'MM 330');
insert into 'enemies' ('name','cr','reference') values ('Homunculus', '0', 'MM 188');
insert into 'enemies' ('name','cr','reference') values ('Hyena', '0', 'MM 331');
insert into 'enemies' ('name','cr','reference') values ('Jackal', '0', 'MM 331');
insert into 'enemies' ('name','cr','reference') values ('Lemure', '0', 'MM 76');
insert into 'enemies' ('name','cr','reference') values ('Lizard', '0', 'MM 332');
insert into 'enemies' ('name','cr','reference') values ('Myconid Sprout', '0', 'MM 230');
insert into 'enemies' ('name','cr','reference') values ('Octopus', '0', 'MM 333');
insert into 'enemies' ('name','cr','reference') values ('Owl', '0', 'MM 333');
insert into 'enemies' ('name','cr','reference') values ('Quipper', '0', 'MM 335');
insert into 'enemies' ('name','cr','reference') values ('Rat', '0', 'MM 335');
insert into 'enemies' ('name','cr','reference') values ('Raven', '0', 'MM 335');
insert into 'enemies' ('name','cr','reference') values ('Scorpion', '0', 'MM 337');
insert into 'enemies' ('name','cr','reference') values ('Shrieker', '0', 'MM 138');
insert into 'enemies' ('name','cr','reference') values ('Spider', '0', 'MM 337');
insert into 'enemies' ('name','cr','reference') values ('Vulture', '0', 'MM 339');
insert into 'enemies' ('name','cr','reference') values ('Weasel', '0', 'MM 340');
insert into 'enemies' ('name','cr','reference') values ('Blood Hawk', '1/8', 'MM 319');
insert into 'enemies' ('name','cr','reference') values ('Camel', '1/8', 'MM 320');
insert into 'enemies' ('name','cr','reference') values ('Flumph', '1/8', 'MM 135');
insert into 'enemies' ('name','cr','reference') values ('Flying Snake', '1/8', 'MM 322');
insert into 'enemies' ('name','cr','reference') values ('Giant Crab', '1/8', 'MM 324');
insert into 'enemies' ('name','cr','reference') values ('Giant Rat', '1/8', 'MM 327');
insert into 'enemies' ('name','cr','reference') values ('Giant Weasel', '1/8', 'MM 329');
insert into 'enemies' ('name','cr','reference') values ('Kobold', '1/8', 'MM 195');
insert into 'enemies' ('name','cr','reference') values ('Manes', '1/8', 'MM 60');
insert into 'enemies' ('name','cr','reference') values ('Mastiff', '1/8', 'MM 332');
insert into 'enemies' ('name','cr','reference') values ('Merfolk', '1/8', 'MM 218');
insert into 'enemies' ('name','cr','reference') values ('Monodrone', '1/8', 'MM 224');
insert into 'enemies' ('name','cr','reference') values ('Mule', '1/8', 'MM 333');
insert into 'enemies' ('name','cr','reference') values ('Poisonous Snake', '1/8', 'MM 334');
insert into 'enemies' ('name','cr','reference') values ('Pony', '1/8', 'MM 335');
insert into 'enemies' ('name','cr','reference') values ('Slaad Tadpole', '1/8', 'MM 276');
insert into 'enemies' ('name','cr','reference') values ('Stirge', '1/8', 'MM 284');
insert into 'enemies' ('name','cr','reference') values ('Twig Blight', '1/8', 'MM 32');
insert into 'enemies' ('name','cr','reference') values ('Aarakocra', '1/4', 'MM 12');
insert into 'enemies' ('name','cr','reference') values ('Axe Beak', '1/4', 'MM 317');
insert into 'enemies' ('name','cr','reference') values ('Blink Dog', '1/4', 'MM 318');
insert into 'enemies' ('name','cr','reference') values ('Boar', '1/4', 'MM 319');
insert into 'enemies' ('name','cr','reference') values ('Bullywug', '1/4', 'MM 35');
insert into 'enemies' ('name','cr','reference') values ('Constrictor Snake', '1/4', 'MM 320');
insert into 'enemies' ('name','cr','reference') values ('Draft Horse', '1/4', 'MM 321');
insert into 'enemies' ('name','cr','reference') values ('Dretch', '1/4', 'MM 57');
insert into 'enemies' ('name','cr','reference') values ('Drow', '1/4', 'MM 128');
insert into 'enemies' ('name','cr','reference') values ('Duodrone', '1/4', 'MM 225');
insert into 'enemies' ('name','cr','reference') values ('Elk', '1/4', 'MM 322');
insert into 'enemies' ('name','cr','reference') values ('Flying Sword', '1/4', 'MM 20');
insert into 'enemies' ('name','cr','reference') values ('Giant Badger', '1/4', 'MM 323');
insert into 'enemies' ('name','cr','reference') values ('Giant Bat', '1/4', 'MM 323');
insert into 'enemies' ('name','cr','reference') values ('Giant Centipede', '1/4', 'MM 323');
insert into 'enemies' ('name','cr','reference') values ('Giant Frog', '1/4', 'MM 325');
insert into 'enemies' ('name','cr','reference') values ('Giant Lizard', '1/4', 'MM 326');
insert into 'enemies' ('name','cr','reference') values ('Giant Owl', '1/4', 'MM 327');
insert into 'enemies' ('name','cr','reference') values ('Giant Poisonous Snake', '1/4', 'MM 327');
insert into 'enemies' ('name','cr','reference') values ('Giant Wolf Spider', '1/4', 'MM 330');
insert into 'enemies' ('name','cr','reference') values ('Goblin', '1/4', 'MM 166');
insert into 'enemies' ('name','cr','reference') values ('Grimlock', '1/4', 'MM 175');
insert into 'enemies' ('name','cr','reference') values ('Kenku', '1/4', 'MM 194');
insert into 'enemies' ('name','cr','reference') values ('Kuo-toa', '1/4', 'MM 199');
insert into 'enemies' ('name','cr','reference') values ('Mud Mephit', '1/4', 'MM 216');
insert into 'enemies' ('name','cr','reference') values ('Needle Blight', '1/4', 'MM 32');
insert into 'enemies' ('name','cr','reference') values ('Panther', '1/4', 'MM 333');
insert into 'enemies' ('name','cr','reference') values ('Pixie', '1/4', 'MM 253');
insert into 'enemies' ('name','cr','reference') values ('Pseudodragon', '1/4', 'MM 254');
insert into 'enemies' ('name','cr','reference') values ('Pteranodon', '1/4', 'MM 80');
insert into 'enemies' ('name','cr','reference') values ('Riding Horse', '1/4', 'MM 336');
insert into 'enemies' ('name','cr','reference') values ('Skeleton', '1/4', 'MM 272');
insert into 'enemies' ('name','cr','reference') values ('Smoke Mephit', '1/4', 'MM 217');
insert into 'enemies' ('name','cr','reference') values ('Sprite', '1/4', 'MM 283');
insert into 'enemies' ('name','cr','reference') values ('Steam Mephit', '1/4', 'MM 217');
insert into 'enemies' ('name','cr','reference') values ('Swarm of Bats', '1/4', 'MM 337');
insert into 'enemies' ('name','cr','reference') values ('Swarm of Rats', '1/4', 'MM 339');
insert into 'enemies' ('name','cr','reference') values ('Swarm of Ravens', '1/4', 'MM 339');
insert into 'enemies' ('name','cr','reference') values ('Troglodyte', '1/4', 'MM 290');
insert into 'enemies' ('name','cr','reference') values ('Violet Fungus', '1/4', 'MM 138');
insert into 'enemies' ('name','cr','reference') values ('Winged Kobold', '1/4', 'MM 195');
insert into 'enemies' ('name','cr','reference') values ('Wolf', '1/4', 'MM 341');
insert into 'enemies' ('name','cr','reference') values ('Zombie', '1/4', 'MM 316');
insert into 'enemies' ('name','cr','reference') values ('Ape', '1/2', 'MM 317');
insert into 'enemies' ('name','cr','reference') values ('Black Bear', '1/2', 'MM 318');
insert into 'enemies' ('name','cr','reference') values ('Cockatrice', '1/2', 'MM 42');
insert into 'enemies' ('name','cr','reference') values ('Crocodile', '1/2', 'MM 320');
insert into 'enemies' ('name','cr','reference') values ('Darkmantle', '1/2', 'MM 46');
insert into 'enemies' ('name','cr','reference') values ('Dust Mephit', '1/2', 'MM 215');
insert into 'enemies' ('name','cr','reference') values ('Gas Spore', '1/2', 'MM 138');
insert into 'enemies' ('name','cr','reference') values ('Giant Goat', '1/2', 'MM 326');
insert into 'enemies' ('name','cr','reference') values ('Giant Sea Horse', '1/2', 'MM 328');
insert into 'enemies' ('name','cr','reference') values ('Giant Wasp', '1/2', 'MM 329');
insert into 'enemies' ('name','cr','reference') values ('Gnoll', '1/2', 'MM 163');
insert into 'enemies' ('name','cr','reference') values ('Gray Ooze', '1/2', 'MM 243');
insert into 'enemies' ('name','cr','reference') values ('Hobgoblin', '1/2', 'MM 186');
insert into 'enemies' ('name','cr','reference') values ('Ice Mephit', '1/2', 'MM 215');
insert into 'enemies' ('name','cr','reference') values ('Jackalwere', '1/2', 'MM 193');
insert into 'enemies' ('name','cr','reference') values ('Lizardfolk', '1/2', 'MM 204');
insert into 'enemies' ('name','cr','reference') values ('Magma Mephit', '1/2', 'MM 216');
insert into 'enemies' ('name','cr','reference') values ('Magmin', '1/2', 'MM 212');
insert into 'enemies' ('name','cr','reference') values ('Myconid Adult', '1/2', 'MM 232');
insert into 'enemies' ('name','cr','reference') values ('Orc', '1/2', 'MM 246');
insert into 'enemies' ('name','cr','reference') values ('Piercer', '1/2', 'MM 252');
insert into 'enemies' ('name','cr','reference') values ('Reef Shark', '1/2', 'MM 336');
insert into 'enemies' ('name','cr','reference') values ('Rust Monster', '1/2', 'MM 262');
insert into 'enemies' ('name','cr','reference') values ('Sahuagin', '1/2', 'MM 263');
insert into 'enemies' ('name','cr','reference') values ('Satyr', '1/2', 'MM 267');
insert into 'enemies' ('name','cr','reference') values ('Shadow', '1/2', 'MM 269');
insert into 'enemies' ('name','cr','reference') values ('Svirfneblin', '1/2', 'MM 164');
insert into 'enemies' ('name','cr','reference') values ('Swarm of Insects', '1/2', 'MM 338');
insert into 'enemies' ('name','cr','reference') values ('Tridrone', '1/2', 'MM 225');
insert into 'enemies' ('name','cr','reference') values ('Vine Blight', '1/2', 'MM 32');
insert into 'enemies' ('name','cr','reference') values ('Warhorse', '1/2', 'MM 340');
insert into 'enemies' ('name','cr','reference') values ('Warhorse Skeleton', '1/2', 'MM 273');
insert into 'enemies' ('name','cr','reference') values ('Worg', '1/2', 'MM 341');
insert into 'enemies' ('name','cr','reference') values ('Animated Armor', '1', 'MM 19');
insert into 'enemies' ('name','cr','reference') values ('Brass Dragon Wyrmling', '1', 'MM 106');
insert into 'enemies' ('name','cr','reference') values ('Brown Bear', '1', 'MM 319');
insert into 'enemies' ('name','cr','reference') values ('Bugbear', '1', 'MM 33');
insert into 'enemies' ('name','cr','reference') values ('Copper Dragon Wyrmling', '1', 'MM 112');
insert into 'enemies' ('name','cr','reference') values ('Death Dog', '1', 'MM 321');
insert into 'enemies' ('name','cr','reference') values ('Dire Wolf', '1', 'MM 321');
insert into 'enemies' ('name','cr','reference') values ('Dryad', '1', 'MM 121');
insert into 'enemies' ('name','cr','reference') values ('Duergar', '1', 'MM 122');
insert into 'enemies' ('name','cr','reference') values ('Fire Snake', '1', 'MM 265');
insert into 'enemies' ('name','cr','reference') values ('Ghoul', '1', 'MM 148');
insert into 'enemies' ('name','cr','reference') values ('Giant Eagle', '1', 'MM 324');
insert into 'enemies' ('name','cr','reference') values ('Giant Hyena', '1', 'MM 326');
insert into 'enemies' ('name','cr','reference') values ('Giant Octopus', '1', 'MM 326');
insert into 'enemies' ('name','cr','reference') values ('Giant Spider', '1', 'MM 328');
insert into 'enemies' ('name','cr','reference') values ('Giant Toad', '1', 'MM 329');
insert into 'enemies' ('name','cr','reference') values ('Giant Vulture', '1', 'MM 329');
insert into 'enemies' ('name','cr','reference') values ('Goblin Boss', '1', 'MM 166');
insert into 'enemies' ('name','cr','reference') values ('Half-ogre', '1', 'MM 238');
insert into 'enemies' ('name','cr','reference') values ('Harpy', '1', 'MM 181');
insert into 'enemies' ('name','cr','reference') values ('Hippogriff', '1', 'MM 184');
insert into 'enemies' ('name','cr','reference') values ('Imp', '1', 'MM 76');
insert into 'enemies' ('name','cr','reference') values ('Kuo-toa Whip', '1', 'MM 200');
insert into 'enemies' ('name','cr','reference') values ('Lion', '1', 'MM 331');
insert into 'enemies' ('name','cr','reference') values ('Quadrone', '1', 'MM 226');
insert into 'enemies' ('name','cr','reference') values ('Quaggoth Spore Servant', '1', 'MM 230');
insert into 'enemies' ('name','cr','reference') values ('Quasit', '1', 'MM 63');
insert into 'enemies' ('name','cr','reference') values ('Scarecrow', '1', 'MM 268');
insert into 'enemies' ('name','cr','reference') values ('Specter', '1', 'MM 279');
insert into 'enemies' ('name','cr','reference') values ('Swarm of Quippers', '1', 'MM 338');
insert into 'enemies' ('name','cr','reference') values ('Thri-kreen', '1', 'MM 288');
insert into 'enemies' ('name','cr','reference') values ('Tiger', '1', 'MM 339');
insert into 'enemies' ('name','cr','reference') values ('Young Faerie Dragon', '1', 'MM 133');
insert into 'enemies' ('name','cr','reference') values ('Yuan-ti Pureblood', '1', 'MM 310');
insert into 'enemies' ('name','cr','reference') values ('Adult Faerie Dragon', '2', 'MM 133');
insert into 'enemies' ('name','cr','reference') values ('Allosaurus', '2', 'MM 79');
insert into 'enemies' ('name','cr','reference') values ('Ankheg', '2', 'MM 21');
insert into 'enemies' ('name','cr','reference') values ('Awakened Tree', '2', 'MM 317');
insert into 'enemies' ('name','cr','reference') values ('Azer', '2', 'MM 22');
insert into 'enemies' ('name','cr','reference') values ('Black Dragon Wyrmling', '2', 'MM 88');
insert into 'enemies' ('name','cr','reference') values ('Bronze Dragon Wyrmling', '2', 'MM 109');
insert into 'enemies' ('name','cr','reference') values ('Carrion Crawler', '2', 'MM 37');
insert into 'enemies' ('name','cr','reference') values ('Cave Bear', '2', 'MM 334');
insert into 'enemies' ('name','cr','reference') values ('Centaur', '2', 'MM 38');
insert into 'enemies' ('name','cr','reference') values ('Ettercap', '2', 'MM 131');
insert into 'enemies' ('name','cr','reference') values ('Gargoyle', '2', 'MM 140');
insert into 'enemies' ('name','cr','reference') values ('Gelatinous Cube', '2', 'MM 242');
insert into 'enemies' ('name','cr','reference') values ('Ghast', '2', 'MM 148');
insert into 'enemies' ('name','cr','reference') values ('Giant Boar', '2', 'MM 323');
insert into 'enemies' ('name','cr','reference') values ('Giant Constrictor Snake', '2', 'MM 324');
insert into 'enemies' ('name','cr','reference') values ('Giant Elk', '2', 'MM 325');
insert into 'enemies' ('name','cr','reference') values ('Gibbering Mouther', '2', 'MM 157');
insert into 'enemies' ('name','cr','reference') values ('Githzerai Monk', '2', 'MM 161');
insert into 'enemies' ('name','cr','reference') values ('Gnoll Pack Lord', '2', 'MM 163');
insert into 'enemies' ('name','cr','reference') values ('Green Dragon Wyrmling', '2', 'MM 95');
insert into 'enemies' ('name','cr','reference') values ('Grick', '2', 'MM 173');
insert into 'enemies' ('name','cr','reference') values ('Griffon', '2', 'MM 174');
insert into 'enemies' ('name','cr','reference') values ('Hunter Shark', '2', 'MM 330');
insert into 'enemies' ('name','cr','reference') values ('Intellect Devourer', '2', 'MM 191');
insert into 'enemies' ('name','cr','reference') values ('Lizardfolk Shaman', '2', 'MM 205');
insert into 'enemies' ('name','cr','reference') values ('Merrow', '2', 'MM 219');
insert into 'enemies' ('name','cr','reference') values ('Mimic', '2', 'MM 220');
insert into 'enemies' ('name','cr','reference') values ('Minotaur Skeleton', '2', 'MM 273');
insert into 'enemies' ('name','cr','reference') values ('Myconid Sovereign', '2', 'MM 232');
insert into 'enemies' ('name','cr','reference') values ('Nothic', '2', 'MM 236');
insert into 'enemies' ('name','cr','reference') values ('Ochre Jelly', '2', 'MM 243');
insert into 'enemies' ('name','cr','reference') values ('Ogre', '2', 'MM 237');
insert into 'enemies' ('name','cr','reference') values ('Ogre Zombie', '2', 'MM 316');
insert into 'enemies' ('name','cr','reference') values ('Orc Eye of Gruumsh', '2', 'MM 247');
insert into 'enemies' ('name','cr','reference') values ('Orog', '2', 'MM 247');
insert into 'enemies' ('name','cr','reference') values ('Pegasus', '2', 'MM 250');
insert into 'enemies' ('name','cr','reference') values ('Pentadrone', '2', 'MM 226');
insert into 'enemies' ('name','cr','reference') values ('Peryton', '2', 'MM 251');
insert into 'enemies' ('name','cr','reference') values ('Plesiosaurus', '2', 'MM 80');
insert into 'enemies' ('name','cr','reference') values ('Polar Bear', '2', 'MM 334');
insert into 'enemies' ('name','cr','reference') values ('Quaggoth', '2', 'MM 256');
insert into 'enemies' ('name','cr','reference') values ('Rhinoceros', '2', 'MM 336');
insert into 'enemies' ('name','cr','reference') values ('Rug of Smothering', '2', 'MM 20');
insert into 'enemies' ('name','cr','reference') values ('Saber-toothed Tiger', '2', 'MM 336');
insert into 'enemies' ('name','cr','reference') values ('Sahuagin Priestess', '2', 'MM 264');
insert into 'enemies' ('name','cr','reference') values ('Sea Hag', '2', 'MM 179');
insert into 'enemies' ('name','cr','reference') values ('Silver Dragon Wyrmling', '2', 'MM 118');
insert into 'enemies' ('name','cr','reference') values ('Specter (poltergeist)', '2', 'MM 279');
insert into 'enemies' ('name','cr','reference') values ('Spined Devil', '2', 'MM 78');
insert into 'enemies' ('name','cr','reference') values ('Swarm of Poisonous Snakes', '2', 'MM 338');
insert into 'enemies' ('name','cr','reference') values ('Wererat', '2', 'MM 209');
insert into 'enemies' ('name','cr','reference') values ('White Dragon Wyrmling', '2', 'MM 102');
insert into 'enemies' ('name','cr','reference') values ('Will-o-wisp', '2', 'MM 301');
insert into 'enemies' ('name','cr','reference') values ('Ankylosaurus', '3', 'MM 79');
insert into 'enemies' ('name','cr','reference') values ('Basilisk', '3', 'MM 24');
insert into 'enemies' ('name','cr','reference') values ('Bearded Devil', '3', 'MM 70');
insert into 'enemies' ('name','cr','reference') values ('Blue Dragon Wyrmling', '3', 'MM 91');
insert into 'enemies' ('name','cr','reference') values ('Bugbear Chief', '3', 'MM 33');
insert into 'enemies' ('name','cr','reference') values ('Displacer Beast', '3', 'MM 81');
insert into 'enemies' ('name','cr','reference') values ('Doppelganger', '3', 'MM 82');
insert into 'enemies' ('name','cr','reference') values ('Giant Scorpion', '3', 'MM 327');
insert into 'enemies' ('name','cr','reference') values ('Githyanki Warrior', '3', 'MM 160');
insert into 'enemies' ('name','cr','reference') values ('Gold Dragon Wyrmling', '3', 'MM 115');
insert into 'enemies' ('name','cr','reference') values ('Green Hag', '3', 'MM 177');
insert into 'enemies' ('name','cr','reference') values ('Grell', '3', 'MM 172');
insert into 'enemies' ('name','cr','reference') values ('Hell Hound', '3', 'MM 182');
insert into 'enemies' ('name','cr','reference') values ('Hobgoblin Captain', '3', 'MM 186');
insert into 'enemies' ('name','cr','reference') values ('Hook Horror', '3', 'MM 189');
insert into 'enemies' ('name','cr','reference') values ('Killer Whale', '3', 'MM 331');
insert into 'enemies' ('name','cr','reference') values ('Manticore', '3', 'MM 213');
insert into 'enemies' ('name','cr','reference') values ('Minotaur', '3', 'MM 223');
insert into 'enemies' ('name','cr','reference') values ('Mummy', '3', 'MM 228');
insert into 'enemies' ('name','cr','reference') values ('Nightmare', '3', 'MM 235');
insert into 'enemies' ('name','cr','reference') values ('Owlbear', '3', 'MM 249');
insert into 'enemies' ('name','cr','reference') values ('Phase Spider', '3', 'MM 334');
insert into 'enemies' ('name','cr','reference') values ('Quaggoth Thonot', '3', 'MM 256');
insert into 'enemies' ('name','cr','reference') values ('Spectator', '3', 'MM 30');
insert into 'enemies' ('name','cr','reference') values ('Water Weird', '3', 'MM 299');
insert into 'enemies' ('name','cr','reference') values ('Werewolf', '3', 'MM 211');
insert into 'enemies' ('name','cr','reference') values ('Wight', '3', 'MM 300');
insert into 'enemies' ('name','cr','reference') values ('Winter Wolf', '3', 'MM 340');
insert into 'enemies' ('name','cr','reference') values ('Yeti', '3', 'MM 305');
insert into 'enemies' ('name','cr','reference') values ('Yuan-ti Malison', '3', 'MM 309');
insert into 'enemies' ('name','cr','reference') values ('Banshee', '4', 'MM 23');
insert into 'enemies' ('name','cr','reference') values ('Black Pudding', '4', 'MM 241');
insert into 'enemies' ('name','cr','reference') values ('Bone Naga', '4', 'MM 233');
insert into 'enemies' ('name','cr','reference') values ('Chuul', '4', 'MM 40');
insert into 'enemies' ('name','cr','reference') values ('Couatl', '4', 'MM 43');
insert into 'enemies' ('name','cr','reference') values ('Elephant', '4', 'MM 322');
insert into 'enemies' ('name','cr','reference') values ('Ettin', '4', 'MM 132');
insert into 'enemies' ('name','cr','reference') values ('Flameskull', '4', 'MM 134');
insert into 'enemies' ('name','cr','reference') values ('Ghost', '4', 'MM 147');
insert into 'enemies' ('name','cr','reference') values ('Gnoll Fang of Yeenoghu', '4', 'MM 163');
insert into 'enemies' ('name','cr','reference') values ('Helmed Horror', '4', 'MM 183');
insert into 'enemies' ('name','cr','reference') values ('Incubus', '4', 'MM 285');
insert into 'enemies' ('name','cr','reference') values ('Lamia', '4', 'MM 201');
insert into 'enemies' ('name','cr','reference') values ('Lizard King/Queen', '4', 'MM 205');
insert into 'enemies' ('name','cr','reference') values ('Orc War Chief', '4', 'MM 246');
insert into 'enemies' ('name','cr','reference') values ('Red Dragon Wyrmling', '4', 'MM 98');
insert into 'enemies' ('name','cr','reference') values ('Shadow Demon', '4', 'MM 64');
insert into 'enemies' ('name','cr','reference') values ('Succubus', '4', 'MM 285');
insert into 'enemies' ('name','cr','reference') values ('Wereboar', '4', 'MM 209');
insert into 'enemies' ('name','cr','reference') values ('Weretiger', '4', 'MM 210');
insert into 'enemies' ('name','cr','reference') values ('Air Elemental', '5', 'MM 124');
insert into 'enemies' ('name','cr','reference') values ('Barbed Devil', '5', 'MM 70');
insert into 'enemies' ('name','cr','reference') values ('Barlgura', '5', 'MM 56');
insert into 'enemies' ('name','cr','reference') values ('Beholder Zombie', '5', 'MM 316');
insert into 'enemies' ('name','cr','reference') values ('Bulette', '5', 'MM 34');
insert into 'enemies' ('name','cr','reference') values ('Cambion', '5', 'MM 36');
insert into 'enemies' ('name','cr','reference') values ('Drow Elite Warrior', '5', 'MM 128');
insert into 'enemies' ('name','cr','reference') values ('Earth Elemental', '5', 'MM 124');
insert into 'enemies' ('name','cr','reference') values ('Fire Elemental', '5', 'MM 125');
insert into 'enemies' ('name','cr','reference') values ('Flesh Golem', '5', 'MM 169');
insert into 'enemies' ('name','cr','reference') values ('Giant Crocodile', '5', 'MM 324');
insert into 'enemies' ('name','cr','reference') values ('Giant Shark', '5', 'MM 328');
insert into 'enemies' ('name','cr','reference') values ('Gorgon', '5', 'MM 171');
insert into 'enemies' ('name','cr','reference') values ('Half-Red Dragon Veteran', '5', 'MM 180');
insert into 'enemies' ('name','cr','reference') values ('Hill Giant', '5', 'MM 155');
insert into 'enemies' ('name','cr','reference') values ('Mezzoloth', '5', 'MM 313');
insert into 'enemies' ('name','cr','reference') values ('Night Hag', '5', 'MM 178');
insert into 'enemies' ('name','cr','reference') values ('Otyugh', '5', 'MM 248');
insert into 'enemies' ('name','cr','reference') values ('Red Slaad', '5', 'MM 276');
insert into 'enemies' ('name','cr','reference') values ('Revenant', '5', 'MM 259');
insert into 'enemies' ('name','cr','reference') values ('Roper', '5', 'MM 261');
insert into 'enemies' ('name','cr','reference') values ('Sahuagin Baron', '5', 'MM 264');
insert into 'enemies' ('name','cr','reference') values ('Salamander', '5', 'MM 266');
insert into 'enemies' ('name','cr','reference') values ('Shambling Mound', '5', 'MM 270');
insert into 'enemies' ('name','cr','reference') values ('Triceratops', '5', 'MM 80');
insert into 'enemies' ('name','cr','reference') values ('Troll', '5', 'MM 291');
insert into 'enemies' ('name','cr','reference') values ('Umber Hulk', '5', 'MM 292');
insert into 'enemies' ('name','cr','reference') values ('Unicorn', '5', 'MM 294');
insert into 'enemies' ('name','cr','reference') values ('Vampire Spawn', '5', 'MM 298');
insert into 'enemies' ('name','cr','reference') values ('Water Elemental', '5', 'MM 125');
insert into 'enemies' ('name','cr','reference') values ('Werebear', '5', 'MM 208');
insert into 'enemies' ('name','cr','reference') values ('Wraith', '5', 'MM 302');
insert into 'enemies' ('name','cr','reference') values ('Xorn', '5', 'MM 304');
insert into 'enemies' ('name','cr','reference') values ('Young Remorhaz', '5', 'MM 258');
insert into 'enemies' ('name','cr','reference') values ('Chasme', '6', 'MM 57');
insert into 'enemies' ('name','cr','reference') values ('Chimera', '6', 'MM 39');
insert into 'enemies' ('name','cr','reference') values ('Cyclops', '6', 'MM 45');
insert into 'enemies' ('name','cr','reference') values ('Drider', '6', 'MM 120');
insert into 'enemies' ('name','cr','reference') values ('Galeb Duhr', '6', 'MM 139');
insert into 'enemies' ('name','cr','reference') values ('Githzerai Zerth', '6', 'MM 161');
insert into 'enemies' ('name','cr','reference') values ('Hobgoblin Warlord', '6', 'MM 187');
insert into 'enemies' ('name','cr','reference') values ('Invisible Stalker', '6', 'MM 192');
insert into 'enemies' ('name','cr','reference') values ('Kuo-toa Archpriest', '6', 'MM 200');
insert into 'enemies' ('name','cr','reference') values ('Mammoth', '6', 'MM 332');
insert into 'enemies' ('name','cr','reference') values ('Medusa', '6', 'MM 214');
insert into 'enemies' ('name','cr','reference') values ('Vrock', '6', 'MM 64');
insert into 'enemies' ('name','cr','reference') values ('Wyvern', '6', 'MM 303');
insert into 'enemies' ('name','cr','reference') values ('Young Brass Dragon', '6', 'MM 105');
insert into 'enemies' ('name','cr','reference') values ('Young White Dragon', '6', 'MM 101');
insert into 'enemies' ('name','cr','reference') values ('Blue Slaad', '7', 'MM 276');
insert into 'enemies' ('name','cr','reference') values ('Drow Mage', '7', 'MM 129');
insert into 'enemies' ('name','cr','reference') values ('Giant Ape', '7', 'MM 323');
insert into 'enemies' ('name','cr','reference') values ('Grick Alpha', '7', 'MM 173');
insert into 'enemies' ('name','cr','reference') values ('Mind Flayer', '7', 'MM 222');
insert into 'enemies' ('name','cr','reference') values ('Oni', '7', 'MM 239');
insert into 'enemies' ('name','cr','reference') values ('Shield Guardian', '7', 'MM 271');
insert into 'enemies' ('name','cr','reference') values ('Stone Giant', '7', 'MM 156');
insert into 'enemies' ('name','cr','reference') values ('Young Black Dragon', '7', 'MM 88');
insert into 'enemies' ('name','cr','reference') values ('Young Copper Dragon', '7', 'MM 111');
insert into 'enemies' ('name','cr','reference') values ('Yuan-ti Abomination', '7', 'MM 308');
insert into 'enemies' ('name','cr','reference') values ('Chain Devil', '8', 'MM 72');
insert into 'enemies' ('name','cr','reference') values ('Cloaker', '8', 'MM 41');
insert into 'enemies' ('name','cr','reference') values ('Drow Priestess of Lolth', '8', 'MM 129');
insert into 'enemies' ('name','cr','reference') values ('Fomorian', '8', 'MM 136');
insert into 'enemies' ('name','cr','reference') values ('Frost Giant', '8', 'MM 155');
insert into 'enemies' ('name','cr','reference') values ('Githyanki Knight', '8', 'MM 160');
insert into 'enemies' ('name','cr','reference') values ('Green Slaad', '8', 'MM 277');
insert into 'enemies' ('name','cr','reference') values ('Hezrou', '8', 'MM 60');
insert into 'enemies' ('name','cr','reference') values ('Hydra', '8', 'MM 190');
insert into 'enemies' ('name','cr','reference') values ('Mind Flayer Arcanist', '8', 'MM 222');
insert into 'enemies' ('name','cr','reference') values ('Spirit Naga', '8', 'MM 234');
insert into 'enemies' ('name','cr','reference') values ('Tyrannosaurus Rex', '8', 'MM 80');
insert into 'enemies' ('name','cr','reference') values ('Young Bronze Dragon', '8', 'MM 108');
insert into 'enemies' ('name','cr','reference') values ('Young Green Dragon', '8', 'MM 94');
insert into 'enemies' ('name','cr','reference') values ('Abominable Yeti', '9', 'MM 306');
insert into 'enemies' ('name','cr','reference') values ('Bone Devil', '9', 'MM 71');
insert into 'enemies' ('name','cr','reference') values ('Clay Golem', '9', 'MM 168');
insert into 'enemies' ('name','cr','reference') values ('Cloud Giant', '9', 'MM 154');
insert into 'enemies' ('name','cr','reference') values ('Fire Giant', '9', 'MM 154');
insert into 'enemies' ('name','cr','reference') values ('Glabrezu', '9', 'MM 58');
insert into 'enemies' ('name','cr','reference') values ('Gray Slaad', '9', 'MM 277');
insert into 'enemies' ('name','cr','reference') values ('Nycaloth', '9', 'MM 314');
insert into 'enemies' ('name','cr','reference') values ('Treant', '9', 'MM 289');
insert into 'enemies' ('name','cr','reference') values ('Young Blue Dragon', '9', 'MM 91');
insert into 'enemies' ('name','cr','reference') values ('Young Silver Dragon', '9', 'MM 118');
insert into 'enemies' ('name','cr','reference') values ('Aboleth', '10', 'MM 13');
insert into 'enemies' ('name','cr','reference') values ('Death Slaad', '10', 'MM 278');
insert into 'enemies' ('name','cr','reference') values ('Deva', '10', 'MM 16');
insert into 'enemies' ('name','cr','reference') values ('Guardian Naga', '10', 'MM 234');
insert into 'enemies' ('name','cr','reference') values ('Stone Golem', '10', 'MM 170');
insert into 'enemies' ('name','cr','reference') values ('Yochlol', '10', 'MM 65');
insert into 'enemies' ('name','cr','reference') values ('Young Gold Dragon', '10', 'MM 115');
insert into 'enemies' ('name','cr','reference') values ('Young Red Dragon', '10', 'MM 98');
insert into 'enemies' ('name','cr','reference') values ('Behir', '11', 'MM 25');
insert into 'enemies' ('name','cr','reference') values ('Dao', '11', 'MM 143');
insert into 'enemies' ('name','cr','reference') values ('Djinni', '11', 'MM 144');
insert into 'enemies' ('name','cr','reference') values ('Efreeti', '11', 'MM 145');
insert into 'enemies' ('name','cr','reference') values ('Gynosphinx', '11', 'MM 282');
insert into 'enemies' ('name','cr','reference') values ('Horned Devil', '11', 'MM 74');
insert into 'enemies' ('name','cr','reference') values ('Marid', '11', 'MM 146');
insert into 'enemies' ('name','cr','reference') values ('Remorhaz', '11', 'MM 258');
insert into 'enemies' ('name','cr','reference') values ('Roc', '11', 'MM 260');
insert into 'enemies' ('name','cr','reference') values ('Arcanaloth', '12', 'MM 313');
insert into 'enemies' ('name','cr','reference') values ('Erinyes', '12', 'MM 73');
insert into 'enemies' ('name','cr','reference') values ('Adult Brass Dragon', '13', 'MM 105');
insert into 'enemies' ('name','cr','reference') values ('Adult White Dragon', '13', 'MM 101');
insert into 'enemies' ('name','cr','reference') values ('Beholder', '13', 'MM 28');
insert into 'enemies' ('name','cr','reference') values ('Nalfeshnee', '13', 'MM 62');
insert into 'enemies' ('name','cr','reference') values ('Rakshasa', '13', 'MM 257');
insert into 'enemies' ('name','cr','reference') values ('Storm Giant', '13', 'MM 156');
insert into 'enemies' ('name','cr','reference') values ('Ultroloth', '13', 'MM 314');
insert into 'enemies' ('name','cr','reference') values ('Vampire', '13', 'MM 297');
insert into 'enemies' ('name','cr','reference') values ('Young Red Shadow Dragon', '13', 'MM 85');
insert into 'enemies' ('name','cr','reference') values ('Adult Black Dragon', '14', 'MM 88');
insert into 'enemies' ('name','cr','reference') values ('Adult Copper Dragon', '14', 'MM 111');
insert into 'enemies' ('name','cr','reference') values ('Beholder (in lair)', '14', 'MM 28');
insert into 'enemies' ('name','cr','reference') values ('Death Tyrant', '14', 'MM 29');
insert into 'enemies' ('name','cr','reference') values ('Ice Devil', '14', 'MM 75');
insert into 'enemies' ('name','cr','reference') values ('Adult Bronze Dragon', '15', 'MM 108');
insert into 'enemies' ('name','cr','reference') values ('Adult Green Dragon', '15', 'MM 94');
insert into 'enemies' ('name','cr','reference') values ('Death Tyrant (in lair)', '15', 'MM 29');
insert into 'enemies' ('name','cr','reference') values ('Mummy Lord', '15', 'MM 229');
insert into 'enemies' ('name','cr','reference') values ('Purple Worm', '15', 'MM 255');
insert into 'enemies' ('name','cr','reference') values ('Vampire (spellcaster)', '15', 'MM 297');
insert into 'enemies' ('name','cr','reference') values ('Vampire (warrior)', '15', 'MM 297');
insert into 'enemies' ('name','cr','reference') values ('Adult Blue Dragon', '16', 'MM 91');
insert into 'enemies' ('name','cr','reference') values ('Adult Silver Dragon', '16', 'MM 117');
insert into 'enemies' ('name','cr','reference') values ('Iron Golem', '16', 'MM 170');
insert into 'enemies' ('name','cr','reference') values ('Marilith', '16', 'MM 61');
insert into 'enemies' ('name','cr','reference') values ('Mummy Lord (in lair)', '16', 'MM 229');
insert into 'enemies' ('name','cr','reference') values ('Planetar', '16', 'MM 17');
insert into 'enemies' ('name','cr','reference') values ('Adult Blue Dracolich', '17', 'MM 84');
insert into 'enemies' ('name','cr','reference') values ('Adult Gold Dragon', '17', 'MM 114');
insert into 'enemies' ('name','cr','reference') values ('Adult Red Dragon', '17', 'MM 98');
insert into 'enemies' ('name','cr','reference') values ('Androsphinx', '17', 'MM 281');
insert into 'enemies' ('name','cr','reference') values ('Death Knight', '17', 'MM 47');
insert into 'enemies' ('name','cr','reference') values ('Dragon Turtle', '17', 'MM 119');
insert into 'enemies' ('name','cr','reference') values ('Goristro', '17', 'MM 59');
insert into 'enemies' ('name','cr','reference') values ('Demilich', '18', 'MM 48');
insert into 'enemies' ('name','cr','reference') values ('Balor', '19', 'MM 55');
insert into 'enemies' ('name','cr','reference') values ('Demilich (in lair)', '20', 'MM 48');
insert into 'enemies' ('name','cr','reference') values ('Ancient Brass Dragon', '20', 'MM 104');
insert into 'enemies' ('name','cr','reference') values ('Ancient White Dragon', '20', 'MM 100');
insert into 'enemies' ('name','cr','reference') values ('Pit Fiend', '20', 'MM 77');
insert into 'enemies' ('name','cr','reference') values ('Ancient Black Dragon', '21', 'MM 87');
insert into 'enemies' ('name','cr','reference') values ('Ancient Copper Dragon', '21', 'MM 110');
insert into 'enemies' ('name','cr','reference') values ('Lich', '21', 'MM 202');
insert into 'enemies' ('name','cr','reference') values ('Solar', '21', 'MM 18');
insert into 'enemies' ('name','cr','reference') values ('Ancient Bronze Dragon', '22', 'MM 107');
insert into 'enemies' ('name','cr','reference') values ('Ancient Green Dragon', '22', 'MM 93');
insert into 'enemies' ('name','cr','reference') values ('Lich (in lair)', '22', 'MM 202');
insert into 'enemies' ('name','cr','reference') values ('Ancient Blue Dragon', '23', 'MM 90');
insert into 'enemies' ('name','cr','reference') values ('Ancient Silver Dragon', '23', 'MM 116');
insert into 'enemies' ('name','cr','reference') values ('Empyrean', '23', 'MM 130');
insert into 'enemies' ('name','cr','reference') values ('Kraken', '23', 'MM 197');
insert into 'enemies' ('name','cr','reference') values ('Ancient Gold Dragon', '24', 'MM 113');
insert into 'enemies' ('name','cr','reference') values ('Ancient Red Dragon', '24', 'MM 97');
insert into 'enemies' ('name','cr','reference') values ('Tarrasque', '30', 'MM 286');